"""Type stubs for oxidize-pdf."""

from oxidize_pdf._oxidize_pdf import (
    BatchJob as BatchJob,
    BatchOptions as BatchOptions,
    BatchProcessor as BatchProcessor,
    BatchSummary as BatchSummary,
    Color as Color,
    ComboBox as ComboBox,
    Document as Document,
    EmbeddedFont as EmbeddedFont,
    ExtractImagesOptions as ExtractImagesOptions,
    ExtractedImageData as ExtractedImageData,
    ExtractedText as ExtractedText,
    ExtractionOptions as ExtractionOptions,
    ImageExtractionLimits as ImageExtractionLimits,
    Font as Font,
    JobResult as JobResult,
    Margins as Margins,
    Page as Page,
    ParsedPage as ParsedPage,
    PdfEncryptionError as PdfEncryptionError,
    PdfError as PdfError,
    PdfIoError as PdfIoError,
    PdfParseError as PdfParseError,
    PdfPermissionError as PdfPermissionError,
    PdfReader as PdfReader,
    DecodedGlyph as DecodedGlyph,
    ResolvedEmbeddedFont as ResolvedEmbeddedFont,
    ResolvedFontResource as ResolvedFontResource,
    Type3Font as Type3Font,
    Type3Glyph as Type3Glyph,
    Permissions as Permissions,
    Point as Point,
    ProgressInfo as ProgressInfo,
    Rectangle as Rectangle,
    TextAlign as TextAlign,
    TextField as TextField,
    TextFragment as TextFragment,
    TextRenderingMode as TextRenderingMode,
    SpaceDecision as SpaceDecision,
    __version__ as __version__,
    batch_merge_pdfs as batch_merge_pdfs,
    batch_split_pdfs as batch_split_pdfs,
    extract_images_from_pdf as extract_images_from_pdf,
    extract_images_in_memory as extract_images_in_memory,
    extract_pages as extract_pages,
    merge_pdfs as merge_pdfs,
    rotate_pdf as rotate_pdf,
    split_pdf as split_pdf,
)

__all__: list[str]

from oxidize_pdf._oxidize_pdf import (
    DocumentMetadata as DocumentMetadata,
    TextChunk as TextChunk,
    DocumentChunk as DocumentChunk,
    RagChunk as RagChunk,
    CorruptionReport as CorruptionReport,
    PdfAValidationResult as PdfAValidationResult,
    ValidationResult as ValidationResult,
    OverlayPosition as OverlayPosition,
    OverlayOptions as OverlayOptions,
    Annotation as Annotation,
    TextAnnotation as TextAnnotation,
    HighlightAnnotation as HighlightAnnotation,
    CorruptionType as CorruptionType,
    PdfALevel as PdfALevel,
    PdfAValidator as PdfAValidator,
    ValidationRule as ValidationRule,
    FieldValue as FieldValue,
    FieldValidator as FieldValidator,
    FormValidationSystem as FormValidationSystem,
    reverse_pdf_pages as reverse_pdf_pages,
    overlay_pdf as overlay_pdf,
    validate_pdf as validate_pdf,
    detect_pdf_corruption as detect_pdf_corruption,
    verify_pdf_signatures as verify_pdf_signatures,
    compare_pdfs as compare_pdfs,
)
