"""Type stubs for oxidize-pdf."""

from oxidize_pdf._oxidize_pdf import (
    BatchJob as BatchJob,
    BatchOptions as BatchOptions,
    BatchProcessor as BatchProcessor,
    BatchSummary as BatchSummary,
    Color as Color,
    ComboBox as ComboBox,
    Document as Document,
    EmbeddedFont as EmbeddedFont,
    Font as Font,
    JobResult as JobResult,
    Margins as Margins,
    Page as Page,
    ParsedPage as ParsedPage,
    PdfEncryptionError as PdfEncryptionError,
    PdfError as PdfError,
    PdfIoError as PdfIoError,
    PdfParseError as PdfParseError,
    PdfPermissionError as PdfPermissionError,
    PdfReader as PdfReader,
    Permissions as Permissions,
    Point as Point,
    ProgressInfo as ProgressInfo,
    Rectangle as Rectangle,
    TextAlign as TextAlign,
    TextField as TextField,
    __version__ as __version__,
    batch_merge_pdfs as batch_merge_pdfs,
    batch_split_pdfs as batch_split_pdfs,
    extract_pages as extract_pages,
    merge_pdfs as merge_pdfs,
    rotate_pdf as rotate_pdf,
    split_pdf as split_pdf,
)

__all__: list[str]
