"""Type stubs for the oxidize-pdf native extension module."""

from typing import Any, BinaryIO, Optional, Union

# ── Module metadata ────────────────────────────────────────────────────────────

__version__: str

# ── Exceptions ─────────────────────────────────────────────────────────────────

class PdfError(Exception):
    """Base exception for all oxidize-pdf errors."""
    ...

class PdfParseError(PdfError):
    """Raised when PDF parsing fails."""
    ...

class PdfIoError(PdfError):
    """Raised on I/O errors (file not found, permission denied, etc.)."""
    ...

class PdfEncryptionError(PdfError):
    """Raised on encryption/decryption errors."""
    ...

class PdfPermissionError(PdfError):
    """Raised when an operation is denied by document permissions."""
    ...

# ── Color ──────────────────────────────────────────────────────────────────────

class Color:
    """A color value in RGB, Gray, or CMYK color space."""

    @staticmethod
    def rgb(r: float, g: float, b: float) -> Color: ...
    @staticmethod
    def gray(value: float) -> Color: ...
    @staticmethod
    def cmyk(c: float, m: float, y: float, k: float) -> Color: ...
    @staticmethod
    def hex(hex_str: str) -> Color: ...
    @staticmethod
    def black() -> Color: ...
    @staticmethod
    def white() -> Color: ...
    @staticmethod
    def red() -> Color: ...
    @staticmethod
    def green() -> Color: ...
    @staticmethod
    def blue() -> Color: ...

    @property
    def r(self) -> float: ...
    @property
    def g(self) -> float: ...
    @property
    def b(self) -> float: ...
    @property
    def gray_value(self) -> float: ...
    @property
    def c(self) -> float: ...
    @property
    def m(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def k(self) -> float: ...
    @property
    def color_space(self) -> str: ...

    def __repr__(self) -> str: ...

# ── Point ──────────────────────────────────────────────────────────────────────

class Point:
    """A 2D point with x and y coordinates."""

    def __init__(self, x: float, y: float) -> None: ...

    @staticmethod
    def origin() -> Point: ...

    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...

    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

# ── Rectangle ──────────────────────────────────────────────────────────────────

class Rectangle:
    """An axis-aligned rectangle defined by two corner points."""

    def __init__(self, lower_left: Point, upper_right: Point) -> None: ...

    @staticmethod
    def from_xywh(x: float, y: float, width: float, height: float) -> Rectangle: ...

    @property
    def lower_left(self) -> Point: ...
    @property
    def upper_right(self) -> Point: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    @property
    def center(self) -> Point: ...

    def __repr__(self) -> str: ...

# ── Margins ────────────────────────────────────────────────────────────────────

class Margins:
    """Page margins (top, right, bottom, left) in points."""

    def __init__(
        self,
        top: float = 0.0,
        right: float = 0.0,
        bottom: float = 0.0,
        left: float = 0.0,
    ) -> None: ...

    @staticmethod
    def uniform(value: float) -> Margins: ...

    @property
    def top(self) -> float: ...
    @property
    def right(self) -> float: ...
    @property
    def bottom(self) -> float: ...
    @property
    def left(self) -> float: ...

    def __repr__(self) -> str: ...

# ── Font ───────────────────────────────────────────────────────────────────────

class Font:
    """Standard PDF fonts. Access as class attributes: ``Font.HELVETICA``, etc."""

    HELVETICA: Font
    HELVETICA_BOLD: Font
    HELVETICA_OBLIQUE: Font
    HELVETICA_BOLD_OBLIQUE: Font
    TIMES_ROMAN: Font
    TIMES_BOLD: Font
    TIMES_ITALIC: Font
    TIMES_BOLD_ITALIC: Font
    COURIER: Font
    COURIER_BOLD: Font
    COURIER_OBLIQUE: Font
    COURIER_BOLD_OBLIQUE: Font
    SYMBOL: Font
    ZAPF_DINGBATS: Font

    def __repr__(self) -> str: ...

class EmbeddedFont:
    """A custom font embedded in a Document, with glyph-coverage diagnostics.

    Obtained from :meth:`Document.embedded_font`.
    """

    @property
    def name(self) -> str: ...
    def has_glyph(self, ch: str) -> bool: ...
    def missing_glyphs(self, text: str) -> list[str]: ...
    def __repr__(self) -> str: ...

# ── TextAlign ──────────────────────────────────────────────────────────────────

class TextAlign:
    """Text alignment options."""

    LEFT: TextAlign
    RIGHT: TextAlign
    CENTER: TextAlign
    JUSTIFIED: TextAlign

    def __repr__(self) -> str: ...

# ── Shadings (gradients, F65 / #297; mesh/conic, core 4.1.0 / #407) ────────────
# Partial stubs: only enough to type :meth:`Page.add_shading`,
# :meth:`Page.add_mesh_shading` and :meth:`Page.add_conic_shading`. The full
# construction surface (linear_gradient, radial_gradient, ShadingManager, …) is
# exposed at runtime but not yet modelled here.

class AxialShading: ...
class RadialShading: ...
class GouraudVertex: ...
class FreeFormGouraudShading: ...
class ConicShading: ...

# ── Page ───────────────────────────────────────────────────────────────────────

class Page:
    """A page in a PDF document for adding text and graphics content."""

    def __init__(self, width: float, height: float) -> None: ...

    @staticmethod
    def a4() -> Page: ...
    @staticmethod
    def a4_landscape() -> Page: ...
    @staticmethod
    def letter() -> Page: ...
    @staticmethod
    def letter_landscape() -> Page: ...
    @staticmethod
    def legal() -> Page: ...
    @staticmethod
    def legal_landscape() -> Page: ...

    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    @property
    def margins(self) -> Margins: ...

    def set_margins(self, margins: Margins) -> None: ...

    # Text operations
    def set_font(self, font: Font, size: float) -> None: ...
    def set_text_color(self, color: Color) -> None: ...
    def set_character_spacing(self, spacing: float) -> None: ...
    def set_word_spacing(self, spacing: float) -> None: ...
    def set_leading(self, leading: float) -> None: ...
    def text_at(self, x: float, y: float, text: str) -> None: ...
    def set_custom_font(self, name: str, size: float) -> None: ...
    def show_cid_array(
        self, elements: list[CidShowElement], x: float, y: float
    ) -> None: ...

    # Graphics operations
    def set_fill_color(self, color: Color) -> None: ...
    def set_stroke_color(self, color: Color) -> None: ...
    def set_line_width(self, width: float) -> None: ...
    def set_fill_opacity(self, opacity: float) -> None: ...
    def set_stroke_opacity(self, opacity: float) -> None: ...
    def draw_rect(self, x: float, y: float, width: float, height: float) -> None: ...
    def draw_circle(self, cx: float, cy: float, radius: float) -> None: ...
    def move_to(self, x: float, y: float) -> None: ...
    def line_to(self, x: float, y: float) -> None: ...
    def curve_to(
        self, x1: float, y1: float, x2: float, y2: float, x3: float, y3: float
    ) -> None: ...
    def close_path(self) -> None: ...
    def fill(self) -> None: ...
    def stroke(self) -> None: ...
    def fill_and_stroke(self) -> None: ...

    # ── Gradient rendering (oxidize-pdf 2.14.0, #297) ────────────────────────
    def clip(self) -> None: ...
    def clip_even_odd(self) -> None: ...
    def end_path(self) -> None: ...
    def add_shading(
        self, name: str, shading: Union["AxialShading", "RadialShading"]
    ) -> None: ...
    def add_mesh_shading(
        self, name: str, shading: "FreeFormGouraudShading"
    ) -> None: ...
    def add_conic_shading(self, name: str, shading: "ConicShading") -> None: ...
    def paint_shading(self, name: str) -> None: ...

    # Page-level colour-space resources (GFX-019, oxidize-pdf 2.11.0)
    def add_color_space(self, name: str, color_space: PageColorSpace) -> None: ...
    def set_fill_color_icc(self, name: str, components: list[float]) -> None: ...
    def set_stroke_color_icc(self, name: str, components: list[float]) -> None: ...
    def set_fill_color_calibrated_named(
        self, name: str, color: CalibratedColor
    ) -> None: ...
    def set_stroke_color_calibrated_named(
        self, name: str, color: CalibratedColor
    ) -> None: ...
    def set_fill_color_lab_named(self, name: str, color: LabColor) -> None: ...
    def set_stroke_color_lab_named(self, name: str, color: LabColor) -> None: ...

    def __repr__(self) -> str: ...

# ── Calibrated colour spaces (Feature 54) ───────────────────────────────────────

class CalGrayColorSpace:
    """CIE-based CalGray colour space (ISO 32000-1 §8.6.5.1)."""

    def __init__(self) -> None: ...
    @staticmethod
    def d50() -> CalGrayColorSpace: ...
    @staticmethod
    def d65() -> CalGrayColorSpace: ...
    def with_gamma(self, gamma: float) -> CalGrayColorSpace: ...
    def with_white_point(self, white_point: list[float]) -> CalGrayColorSpace: ...
    def with_black_point(self, black_point: list[float]) -> CalGrayColorSpace: ...
    @property
    def gamma(self) -> float: ...
    @property
    def white_point(self) -> tuple[float, float, float]: ...
    def __repr__(self) -> str: ...

class CalRgbColorSpace:
    """CIE-based CalRGB colour space (ISO 32000-1 §8.6.5.2)."""

    def __init__(self) -> None: ...
    @staticmethod
    def srgb() -> CalRgbColorSpace: ...
    @staticmethod
    def adobe_rgb() -> CalRgbColorSpace: ...
    @staticmethod
    def d65() -> CalRgbColorSpace: ...
    def with_gamma(self, gamma: list[float]) -> CalRgbColorSpace: ...
    def with_white_point(self, white_point: list[float]) -> CalRgbColorSpace: ...
    def with_matrix(self, matrix: list[float]) -> CalRgbColorSpace: ...
    @property
    def gamma(self) -> tuple[float, float, float]: ...
    def __repr__(self) -> str: ...

class LabColorSpace:
    """CIE Lab colour space (ISO 32000-1 §8.6.5.4)."""

    @staticmethod
    def d50() -> LabColorSpace: ...
    @staticmethod
    def d65() -> LabColorSpace: ...
    def __repr__(self) -> str: ...

class CalibratedColor:
    """A colour value in a calibrated (CalGray/CalRGB) colour space."""

    @staticmethod
    def cal_gray(value: float, cs: CalGrayColorSpace) -> CalibratedColor: ...
    @staticmethod
    def cal_rgb(rgb: list[float], cs: CalRgbColorSpace) -> CalibratedColor: ...
    def values(self) -> list[float]: ...
    def __repr__(self) -> str: ...

class LabColor:
    """A colour value in a Lab colour space."""

    def __init__(self, l: float, a: float, b: float, cs: LabColorSpace) -> None: ...
    @staticmethod
    def white() -> LabColor: ...
    @staticmethod
    def black() -> LabColor: ...
    @staticmethod
    def gray() -> LabColor: ...
    @property
    def l(self) -> float: ...
    @property
    def a(self) -> float: ...
    @property
    def b(self) -> float: ...
    def values(self) -> list[float]: ...
    def delta_e(self, other: LabColor) -> float: ...
    def __repr__(self) -> str: ...

# ── PageColorSpace (GFX-019) ────────────────────────────────────────────────────

class PageColorSpace:
    """A colour space registrable on a page via ``add_color_space`` and emitted
    at ``/Resources/ColorSpace/<name>`` (ISO 32000-1 §8.6)."""

    @staticmethod
    def device(name: str) -> PageColorSpace: ...
    @staticmethod
    def icc_based(n: int, alternate: str) -> PageColorSpace: ...
    @staticmethod
    def cal_gray(cs: CalGrayColorSpace) -> PageColorSpace: ...
    @staticmethod
    def cal_rgb(cs: CalRgbColorSpace) -> PageColorSpace: ...
    @staticmethod
    def lab(cs: LabColorSpace) -> PageColorSpace: ...
    @staticmethod
    def parameterised(family: str, params: dict[str, object]) -> PageColorSpace: ...
    def __repr__(self) -> str: ...

# ── CID-keyed positioned glyph runs (issue #358) ────────────────────────────────

class CidMapping:
    """Mapping that drives a CID-keyed (CID == GID under Identity-H) Type0 font.

    A pre-shaped glyph run is drawn by glyph id. ``cid_to_gid`` says which GID
    each CID renders (for subsetting); ``cid_to_unicode`` / ``cid_to_unicode_str``
    keep the run extractable via the emitted ``ToUnicode`` CMap, the latter
    letting one CID (e.g. an ``fi`` ligature glyph) decompose to several
    characters. ``max_cid`` sizes the ``CIDToGIDMap``; when omitted it is
    derived as the largest CID present across every map.
    """

    def __init__(
        self,
        cid_to_gid: dict[int, int] | None = ...,
        cid_to_unicode: dict[int, int] | None = ...,
        cid_to_unicode_str: dict[int, str] | None = ...,
        max_cid: int | None = ...,
    ) -> None: ...
    @property
    def cid_to_gid(self) -> dict[int, int]: ...
    @property
    def cid_to_unicode(self) -> dict[int, int]: ...
    @property
    def cid_to_unicode_str(self) -> dict[int, str]: ...
    @property
    def max_cid(self) -> int: ...
    def __repr__(self) -> str: ...

class CidShowElement:
    """One glyph in a positioned run drawn by ``Page.show_cid_array``.

    ``cid`` is the 2-byte code (glyph id under Identity) in the active CID-keyed
    font. ``adjust`` is the post-glyph advance kern in thousandths of a
    text-space unit (PDF ``TJ`` convention: positive moves the next glyph left).
    ``x_offset`` displaces this glyph from its pen position without consuming
    advance (GPOS mark attachment / diacritics); defaults to ``0.0``.
    """

    def __init__(self, cid: int, adjust: float) -> None: ...
    def with_x_offset(self, x_offset: float) -> CidShowElement: ...
    @property
    def cid(self) -> int: ...
    @property
    def adjust(self) -> float: ...
    @property
    def x_offset(self) -> float: ...
    def __repr__(self) -> str: ...

# ── Document ───────────────────────────────────────────────────────────────────

class Document:
    """A PDF document that can contain multiple pages and metadata."""

    def __init__(self) -> None: ...

    @property
    def page_count(self) -> int: ...
    @property
    def is_encrypted(self) -> bool: ...

    def set_title(self, title: str) -> None: ...
    def set_author(self, author: str) -> None: ...
    def set_subject(self, subject: str) -> None: ...
    def set_keywords(self, keywords: str) -> None: ...
    def set_creator(self, creator: str) -> None: ...
    def add_page(self, page: Page) -> None: ...
    def new_page_a4(self) -> Page: ...
    def new_page_letter(self) -> Page: ...
    def new_page(self, width: float, height: float) -> Page: ...
    def save(self, path: str) -> None: ...
    def save_to_bytes(self) -> bytes: ...
    def save_with_config(self, path: str, config: WriterConfig) -> None: ...
    def save_to_bytes_with_config(self, config: WriterConfig) -> bytes: ...
    def add_font(self, name: str, path: str) -> None: ...
    def add_font_from_bytes(self, name: str, data: bytes) -> None: ...
    def add_cid_keyed_font(
        self, name: str, data: bytes, mapping: CidMapping
    ) -> None: ...
    def measure_text(self, text: str, font: Font, size: float) -> float: ...
    def measure_char(self, ch: str, font: Font, size: float) -> float: ...
    def embedded_font(self, name: str) -> Optional[EmbeddedFont]: ...
    def font_missing_glyphs(self, font_name: str, text: str) -> list[str]: ...
    def encrypt(
        self,
        user_password: str,
        owner_password: str,
        permissions: Optional[Permissions] = None,
    ) -> None: ...

    def __repr__(self) -> str: ...

# ── Form fields ───────────────────────────────────────────────────────────────

class TextField:
    """Single-line or multiline text input form field."""

    def __init__(self, name: str) -> None: ...

    def with_default_value(self, value: str) -> TextField: ...
    def with_value(self, value: str) -> TextField: ...
    def with_max_length(self, length: int) -> TextField: ...
    def multiline(self) -> TextField: ...
    def password(self) -> TextField: ...
    def with_default_appearance(
        self, font: Font, size: float, color: Color
    ) -> TextField: ...

    def __repr__(self) -> str: ...

class ComboBox:
    """Drop-down combo box form field, optionally editable."""

    def __init__(self, name: str) -> None: ...

    def add_option(self, export_value: str, display: str) -> ComboBox: ...
    def editable(self) -> ComboBox: ...
    def with_value(self, value: str) -> ComboBox: ...
    def with_default_appearance(
        self, font: Font, size: float, color: Color
    ) -> ComboBox: ...

    def __repr__(self) -> str: ...

class IncrementalFormFiller:
    """Fill AcroForm fields on an already-serialized PDF via an ISO 32000-1
    §7.5.6 incremental update, preserving the original bytes verbatim."""

    def __init__(self, base_bytes: bytes) -> None: ...

    def fill(self, field_name: str, value: str) -> bytes: ...
    def fill_many(self, fields: list[tuple[str, str]]) -> bytes: ...

    def __repr__(self) -> str: ...

# ── WriterConfig ───────────────────────────────────────────────────────────────

class WriterConfig:
    """Configuration for the PDF writer: compression, xref/object streams,
    target PDF version, and incremental-update mode."""

    def __init__(
        self,
        compress_streams: Optional[bool] = None,
        use_xref_streams: Optional[bool] = None,
        use_object_streams: Optional[bool] = None,
        pdf_version: Optional[str] = None,
        incremental_update: Optional[bool] = None,
    ) -> None: ...

    @staticmethod
    def modern() -> WriterConfig: ...
    @staticmethod
    def legacy() -> WriterConfig: ...
    @staticmethod
    def incremental() -> WriterConfig: ...

    @property
    def compress_streams(self) -> bool: ...
    @property
    def use_xref_streams(self) -> bool: ...
    @property
    def use_object_streams(self) -> bool: ...
    @property
    def pdf_version(self) -> str: ...
    @property
    def incremental_update(self) -> bool: ...

    def __repr__(self) -> str: ...

# ── ParseOptions ───────────────────────────────────────────────────────────────

class ParseOptions:
    """Configuration for the PDF parser (strictness, recovery, lenient modes)."""

    def __init__(
        self,
        strict_mode: bool = True,
        recover_from_stream_errors: bool = False,
        ignore_corrupt_streams: bool = False,
        partial_content_allowed: bool = False,
        lenient_streams: bool = False,
        lenient_encoding: bool = True,
        lenient_syntax: bool = False,
        max_recovery_attempts: int = 3,
        max_recovery_bytes: int = 1000,
        collect_warnings: bool = False,
    ) -> None: ...

    @staticmethod
    def strict() -> ParseOptions: ...
    @staticmethod
    def tolerant() -> ParseOptions: ...
    @staticmethod
    def lenient() -> ParseOptions: ...
    @staticmethod
    def skip_errors() -> ParseOptions: ...

    @property
    def strict_mode(self) -> bool: ...
    @property
    def recover_from_stream_errors(self) -> bool: ...
    @property
    def ignore_corrupt_streams(self) -> bool: ...
    @property
    def partial_content_allowed(self) -> bool: ...
    @property
    def lenient_streams(self) -> bool: ...
    @property
    def lenient_encoding(self) -> bool: ...
    @property
    def lenient_syntax(self) -> bool: ...
    @property
    def max_recovery_attempts(self) -> int: ...
    @property
    def max_recovery_bytes(self) -> int: ...
    @property
    def collect_warnings(self) -> bool: ...

    def __repr__(self) -> str: ...

# ── PdfReader ──────────────────────────────────────────────────────────────────

class PdfReader:
    """High-level PDF reader for parsing existing PDF files."""

    @staticmethod
    def open(path: str, options: Optional[ParseOptions] = ...) -> PdfReader: ...
    @staticmethod
    def from_bytes(data: bytes, options: Optional[ParseOptions] = ...) -> PdfReader: ...
    @staticmethod
    def from_stream(
        stream: BinaryIO, options: Optional[ParseOptions] = ...
    ) -> PdfReader: ...

    @property
    def is_encrypted(self) -> bool: ...
    @property
    def page_count(self) -> int: ...
    @property
    def version(self) -> str: ...

    def unlock(self, password: str) -> None: ...
    def get_page(self, index: int) -> ParsedPage: ...
    def get_page_resources(self, index: int) -> Optional[PageResources]: ...
    def resolve_font(self, page_index: int, resource_name: str) -> ResolvedFontResource: ...
    def get_page_content_streams(self, index: int) -> list[bytes]: ...
    def extract_text_from_page(self, index: int) -> str: ...
    def extract_text(self) -> list[str]: ...
    def extract_text_from_page_with_reading_order(self, index: int) -> str:
        """Extract flat text from one page in visual reading order."""
        ...
    def extract_text_with_reading_order(self) -> list[str]:
        """Extract flat text from all pages in visual reading order."""
        ...

    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

# ── ParsedPage ─────────────────────────────────────────────────────────────────

class ParsedPage:
    """A page obtained from parsing an existing PDF."""

    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    @property
    def rotation(self) -> int: ...

    def __repr__(self) -> str: ...

# ── Page resources ─────────────────────────────────────────────────────────────

class FontResource:
    """A font referenced by a page's ``/Resources /Font`` sub-dictionary."""

    @property
    def subtype(self) -> str: ...
    @property
    def base_font(self) -> str: ...
    @property
    def encoding(self) -> Optional[str]: ...
    @property
    def is_embedded(self) -> bool: ...
    @property
    def is_subset(self) -> bool: ...
    def __repr__(self) -> str: ...

class ImageResource:
    """An image (``/Subtype /Image`` XObject) referenced by a page's Resources."""

    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def bits_per_component(self) -> int: ...
    @property
    def filter(self) -> list[str]: ...
    @property
    def color_space(self) -> str: ...
    def __repr__(self) -> str: ...

class FormXObjectResource:
    """A Form XObject (``/Subtype /Form``) referenced by a page's Resources."""

    @property
    def bbox(self) -> Optional[tuple[float, float, float, float]]: ...
    def __repr__(self) -> str: ...

class PageResources:
    """Structured view of a page's ``/Resources`` dictionary."""

    @property
    def fonts(self) -> dict[str, FontResource]: ...
    @property
    def images(self) -> dict[str, ImageResource]: ...
    @property
    def forms(self) -> dict[str, FormXObjectResource]: ...
    @property
    def ext_g_states(self) -> dict[str, dict[str, object]]: ...
    @property
    def proc_sets(self) -> list[str]: ...
    @property
    def resource_keys(self) -> list[str]: ...
    def __repr__(self) -> str: ...

class DecodedGlyph:
    @property
    def source_code(self) -> bytes: ...
    @property
    def cid(self) -> Optional[int]: ...
    @property
    def gid(self) -> Optional[int]: ...
    @property
    def unicode(self) -> Optional[str]: ...
    @property
    def advance(self) -> float: ...

class ResolvedEmbeddedFont:
    @property
    def format(self) -> str: ...
    @property
    def data(self) -> bytes: ...

class Type3Glyph:
    @property
    def code(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def width(self) -> float: ...
    @property
    def procedure_width(self) -> tuple[float, float]: ...
    @property
    def bbox(self) -> Optional[tuple[float, float, float, float]]: ...
    @property
    def operations(self) -> list[Any]: ...

class Type3Font:
    @property
    def name(self) -> Optional[str]: ...
    @property
    def font_matrix(self) -> tuple[float, float, float, float, float, float]: ...
    @property
    def font_bbox(self) -> tuple[float, float, float, float]: ...
    @property
    def glyphs(self) -> list[Type3Glyph]: ...
    def glyph(self, code: int) -> Optional[Type3Glyph]: ...

class ResolvedFontResource:
    @property
    def resource_name(self) -> str: ...
    @property
    def base_font(self) -> Optional[str]: ...
    @property
    def subtype(self) -> str: ...
    @property
    def encoding(self) -> Optional[str]: ...
    @property
    def writing_mode(self) -> str: ...
    @property
    def differences(self) -> dict[int, str]: ...
    @property
    def embedded_font(self) -> Optional[ResolvedEmbeddedFont]: ...
    @property
    def type3(self) -> Optional[Type3Font]: ...
    def decode_glyphs(self, data: bytes) -> list[DecodedGlyph]: ...

# ── Permissions ────────────────────────────────────────────────────────────────

class Permissions:
    """PDF document permissions for encrypted documents."""

    def __init__(
        self,
        print: bool = False,
        copy: bool = False,
        modify_contents: bool = False,
        modify_annotations: bool = False,
        fill_forms: bool = False,
        accessibility: bool = True,
        assemble: bool = False,
        print_high_quality: bool = False,
    ) -> None: ...

    @staticmethod
    def all() -> Permissions: ...
    @staticmethod
    def none() -> Permissions: ...

    @property
    def can_print(self) -> bool: ...
    @property
    def can_copy(self) -> bool: ...
    @property
    def can_modify_contents(self) -> bool: ...
    @property
    def can_modify_annotations(self) -> bool: ...
    @property
    def can_fill_forms(self) -> bool: ...
    @property
    def can_assemble(self) -> bool: ...
    @property
    def can_print_high_quality(self) -> bool: ...

    def __repr__(self) -> str: ...

# ── Operations ─────────────────────────────────────────────────────────────────

class ExtractImagesOptions:
    """Options for :func:`extract_images_from_pdf`.

    Note:
        Image preprocessing (auto rotation-correction, contrast, denoise,
        upscaling, force-grayscale) is unavailable: this build excludes the
        upstream ``external-images`` feature. Extracted images are the raw
        embedded streams (e.g. a ``DCTDecode`` JPEG is returned byte-for-byte),
        so extraction is faithful and lossless, not silently degraded.
    """

    def __init__(
        self,
        output_dir: str,
        extract_inline: Optional[bool] = None,
        min_size: Optional[int] = None,
    ) -> None: ...

class ImageExtractionLimits:
    def __init__(
        self,
        max_images: Optional[int] = None,
        max_encoded_bytes_per_image: Optional[int] = None,
        max_total_encoded_bytes: Optional[int] = None,
        max_decoded_pixels_per_image: Optional[int] = None,
    ) -> None: ...
    @property
    def max_images(self) -> int: ...
    @property
    def max_encoded_bytes_per_image(self) -> int: ...
    @property
    def max_total_encoded_bytes(self) -> int: ...
    @property
    def max_decoded_pixels_per_image(self) -> int: ...

class ExtractedImageData:
    @property
    def page_number(self) -> int: ...
    @property
    def image_index(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def format(self) -> str: ...
    @property
    def data(self) -> bytes: ...

def extract_images_in_memory(
    input: str,
    limits: Optional[ImageExtractionLimits] = None,
    page_number: Optional[int] = None,
) -> list[ExtractedImageData]: ...

def extract_images_from_pdf(
    input: str, options: ExtractImagesOptions
) -> list[dict[str, Any]]:
    """Extract embedded images from ``input`` into ``options.output_dir``.

    Args:
        input: Path to the input PDF file.
        options: Extraction options (output directory, inline flag, min size).

    Returns:
        One dict per extracted image with keys ``page_number``,
        ``image_index``, ``file_path``, ``width`` and ``height``. Each image is
        written as its raw embedded stream (lossless; no preprocessing).

    Raises:
        PdfError: If the input file cannot be read or extraction fails.
    """
    ...

def split_pdf(input_path: str, output_dir: str) -> list[str]:
    """Split a PDF into individual single-page files.

    Args:
        input_path: Path to the input PDF file.
        output_dir: Directory where split pages will be written.

    Returns:
        A list of paths to the created files.

    Raises:
        PdfError: If the input file cannot be read or split.
        PdfIoError: If there is an I/O error.
    """
    ...

def merge_pdfs(input_paths: list[str], output_path: str) -> None:
    """Merge multiple PDF files into a single output file.

    Args:
        input_paths: List of paths to PDF files to merge (in order).
        output_path: Path where the merged PDF will be written.

    Raises:
        PdfError: If any input file cannot be read or the merge fails.
        PdfIoError: If there is an I/O error.
        ValueError: If the input list is empty.
    """
    ...

def rotate_pdf(input_path: str, output_path: str, degrees: int) -> None:
    """Rotate all pages of a PDF by the given angle.

    Args:
        input_path: Path to the input PDF file.
        output_path: Path where the rotated PDF will be written.
        degrees: Rotation angle in degrees. Must be 0, 90, 180, or 270.

    Raises:
        PdfError: If the rotation angle is invalid or the file cannot be processed.
        PdfIoError: If there is an I/O error.
    """
    ...

def extract_pages(input_path: str, output_path: str, page_indices: list[int]) -> None:
    """Extract specific pages from a PDF into a new file.

    Args:
        input_path: Path to the input PDF file.
        output_path: Path where the extracted pages will be written.
        page_indices: List of 0-based page indices to extract.

    Raises:
        PdfError: If a page index is out of bounds or the file cannot be processed.
        PdfIoError: If there is an I/O error.
        ValueError: If the page list is empty.
    """
    ...

# ── Analysis pipeline (RAG) ────────────────────────────────────────────────────

class Element:
    """A single partitioned document element (title, paragraph, table, …).

    Frozen value type produced by the analysis pipeline; constructed natively,
    not from Python.
    """

    @property
    def type_name(self) -> str:
        """Snake-case type name: "title", "paragraph", "table", etc."""
        ...
    @property
    def text(self) -> str:
        """Primary text content of this element."""
        ...
    @property
    def display_text(self) -> str:
        """Human-readable text (tables show pipe-separated rows)."""
        ...
    @property
    def page(self) -> int:
        """Page number (0-indexed) where this element appears."""
        ...
    @property
    def class_label(self) -> Optional[str]:
        """Open class label assigned by a custom ``ElementClassifier`` before
        chunking. ``None`` when no classifier ran or it returned ``None``."""
        ...

    def __repr__(self) -> str: ...

class DocumentSource:
    """Source-document metadata stamped on every chunk a pipeline produces."""

    def __init__(
        self,
        filename: Optional[str] = None,
        doc_hash: Optional[str] = None,
    ) -> None: ...

    @property
    def title(self) -> Optional[str]: ...
    @property
    def author(self) -> Optional[str]: ...
    @property
    def creation_date(self) -> Optional[str]: ...
    @property
    def filename(self) -> Optional[str]: ...
    @property
    def doc_hash(self) -> Optional[str]: ...
    @property
    def total_pages(self) -> Optional[int]: ...

    def __repr__(self) -> str: ...

# ── Experimental analysis SPI ──────────────────────────────────────────────────

class ChunkGroup:
    """An ordered group of elements that form a single chunk.

    Returned by a custom chunking strategy's ``chunk(elements)`` method.
    """

    def __init__(
        self,
        elements: list[Element],
        heading_context: Optional[str] = None,
    ) -> None: ...

    @property
    def elements(self) -> list[Element]:
        """The elements that form this chunk, in order."""
        ...
    @property
    def heading_context(self) -> Optional[str]:
        """Optional heading context to prepend for embedding."""
        ...

    def __repr__(self) -> str: ...

class ClassLabel:
    """An open class label assigned to an element by an ``ElementClassifier``.

    The label is an opaque string — semantics live entirely in the provider.
    """

    def __init__(self, label: str) -> None: ...

    def as_str(self) -> str:
        """The label as a string."""
        ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ClassifyContext:
    """Read-only context handed to an ``ElementClassifier``.

    Constructed natively, not from Python.
    """

    @property
    def elements(self) -> list[Element]:
        """All elements of the document, in order."""
        ...
    @property
    def index(self) -> int:
        """Index of the element currently being classified."""
        ...

    def __repr__(self) -> str: ...

class EnrichContext:
    """Read-only context handed to a ``MetadataEnricher``.

    Constructed natively, not from Python.
    """

    @property
    def text(self) -> str:
        """The chunk's text (elements joined by newlines)."""
        ...
    @property
    def elements(self) -> list[Element]:
        """The elements that compose this chunk, in order."""
        ...
    @property
    def heading_path(self) -> list[str]:
        """The chunk's heading breadcrumb, root → leaf."""
        ...

    def __repr__(self) -> str: ...

class AnalysisPipeline:
    """Composable analysis pipeline with pluggable chunking, classification and
    metadata enrichment.

    Builder methods return a new pipeline; the original is left unchanged. The
    default pipeline (no overrides) reproduces ``PdfReader.rag_chunks`` exactly.
    """

    def __init__(self) -> None: ...

    def with_chunking(self, strategy: Any) -> "AnalysisPipeline":
        """Replace the chunking strategy.

        ``strategy`` must expose
        ``chunk(self, elements: list[Element]) -> list[ChunkGroup]``.
        """
        ...
    def with_max_tokens(self, max_tokens: int) -> "AnalysisPipeline":
        """Set the token budget used to flag oversized chunks."""
        ...
    def with_classifier(self, classifier: Any) -> "AnalysisPipeline":
        """Register a classifier that labels elements before chunking.

        ``classifier`` must expose
        ``classify(self, element: Element, ctx: ClassifyContext) -> ClassLabel | None``.
        """
        ...
    def with_enricher(self, enricher: Any) -> "AnalysisPipeline":
        """Register an enricher that writes provider-specific fields into each
        chunk's ``extra`` bag after metadata is derived.

        ``enricher`` must expose
        ``enrich(self, ctx: EnrichContext, extra: dict[str, Any]) -> None``.
        """
        ...
    def with_source(self, source: DocumentSource) -> "AnalysisPipeline":
        """Stamp source-document metadata on every chunk produced."""
        ...

    def __repr__(self) -> str: ...

# ── Batch processing (F62) ───────────────────────────────────────────────────

class BatchOptions:
    """Options controlling batch execution."""

    def __init__(
        self,
        parallelism: Optional[int] = ...,
        stop_on_error: Optional[bool] = ...,
    ) -> None: ...
    def __repr__(self) -> str: ...

class BatchJob:
    """A single queued batch operation. Construct via the static factories."""

    @staticmethod
    def split(input: str, output_pattern: str, pages_per_file: int) -> BatchJob: ...
    @staticmethod
    def merge(inputs: list[str], output: str) -> BatchJob: ...
    @staticmethod
    def rotate(
        input: str, output: str, rotation: int, pages: Optional[list[int]]
    ) -> BatchJob: ...
    @staticmethod
    def extract(input: str, output: str, pages: list[int]) -> BatchJob: ...
    @staticmethod
    def compress(input: str, output: str, quality: int) -> BatchJob: ...
    def __repr__(self) -> str: ...

class JobResult:
    """Result of a single batch job (read-only)."""

    @property
    def status(self) -> str: ...
    @property
    def job_name(self) -> str: ...
    @property
    def duration_secs(self) -> Optional[float]: ...
    @property
    def error(self) -> Optional[str]: ...
    @property
    def output_files(self) -> list[str]: ...
    def __repr__(self) -> str: ...

class BatchSummary:
    """Summary of a completed batch operation (read-only)."""

    @property
    def total_jobs(self) -> int: ...
    @property
    def successful(self) -> int: ...
    @property
    def failed(self) -> int: ...
    @property
    def cancelled(self) -> bool: ...
    @property
    def duration_secs(self) -> float: ...
    @property
    def results(self) -> list[JobResult]: ...
    def success_rate(self) -> float: ...
    def __repr__(self) -> str: ...

class ProgressInfo:
    """Progress of a running batch operation (read-only)."""

    @property
    def total_jobs(self) -> int: ...
    @property
    def completed_jobs(self) -> int: ...
    @property
    def failed_jobs(self) -> int: ...
    @property
    def running_jobs(self) -> int: ...
    def percentage(self) -> float: ...
    def is_complete(self) -> bool: ...

class BatchProcessor:
    """Queue and execute batch jobs."""

    def __init__(self, options: BatchOptions) -> None: ...
    def add_job(self, job: BatchJob) -> None: ...
    def get_progress(self) -> ProgressInfo: ...
    def cancel(self) -> None: ...
    def is_cancelled(self) -> bool: ...
    def execute(self) -> BatchSummary: ...
    def __repr__(self) -> str: ...

def batch_split_pdfs(
    files: list[str], pages_per_file: int, parallelism: int
) -> BatchSummary: ...
def batch_merge_pdfs(
    merge_groups: list[tuple[list[str], str]], parallelism: int
) -> BatchSummary: ...
