"""Type stubs for the oxidize-pdf native extension module."""

from typing import BinaryIO, Optional, Union

# ── Module metadata ────────────────────────────────────────────────────────────

__version__: str

# ── Exceptions ─────────────────────────────────────────────────────────────────

class PdfError(Exception):
    """Base exception for all oxidize-pdf errors."""
    ...

class PdfParseError(PdfError):
    """Raised when PDF parsing fails."""
    ...

class PdfIoError(PdfError):
    """Raised on I/O errors (file not found, permission denied, etc.)."""
    ...

class PdfEncryptionError(PdfError):
    """Raised on encryption/decryption errors."""
    ...

class PdfPermissionError(PdfError):
    """Raised when an operation is denied by document permissions."""
    ...

# ── Color ──────────────────────────────────────────────────────────────────────

class Color:
    """A color value in RGB, Gray, or CMYK color space."""

    @staticmethod
    def rgb(r: float, g: float, b: float) -> Color: ...
    @staticmethod
    def gray(value: float) -> Color: ...
    @staticmethod
    def cmyk(c: float, m: float, y: float, k: float) -> Color: ...
    @staticmethod
    def hex(hex_str: str) -> Color: ...
    @staticmethod
    def black() -> Color: ...
    @staticmethod
    def white() -> Color: ...
    @staticmethod
    def red() -> Color: ...
    @staticmethod
    def green() -> Color: ...
    @staticmethod
    def blue() -> Color: ...

    @property
    def r(self) -> float: ...
    @property
    def g(self) -> float: ...
    @property
    def b(self) -> float: ...
    @property
    def gray_value(self) -> float: ...
    @property
    def c(self) -> float: ...
    @property
    def m(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def k(self) -> float: ...
    @property
    def color_space(self) -> str: ...

    def __repr__(self) -> str: ...

# ── Point ──────────────────────────────────────────────────────────────────────

class Point:
    """A 2D point with x and y coordinates."""

    def __init__(self, x: float, y: float) -> None: ...

    @staticmethod
    def origin() -> Point: ...

    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...

    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

# ── Rectangle ──────────────────────────────────────────────────────────────────

class Rectangle:
    """An axis-aligned rectangle defined by two corner points."""

    def __init__(self, lower_left: Point, upper_right: Point) -> None: ...

    @staticmethod
    def from_xywh(x: float, y: float, width: float, height: float) -> Rectangle: ...

    @property
    def lower_left(self) -> Point: ...
    @property
    def upper_right(self) -> Point: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    @property
    def center(self) -> Point: ...

    def __repr__(self) -> str: ...

# ── Margins ────────────────────────────────────────────────────────────────────

class Margins:
    """Page margins (top, right, bottom, left) in points."""

    def __init__(
        self,
        top: float = 0.0,
        right: float = 0.0,
        bottom: float = 0.0,
        left: float = 0.0,
    ) -> None: ...

    @staticmethod
    def uniform(value: float) -> Margins: ...

    @property
    def top(self) -> float: ...
    @property
    def right(self) -> float: ...
    @property
    def bottom(self) -> float: ...
    @property
    def left(self) -> float: ...

    def __repr__(self) -> str: ...

# ── Font ───────────────────────────────────────────────────────────────────────

class Font:
    """Standard PDF fonts. Access as class attributes: ``Font.HELVETICA``, etc."""

    HELVETICA: Font
    HELVETICA_BOLD: Font
    HELVETICA_OBLIQUE: Font
    HELVETICA_BOLD_OBLIQUE: Font
    TIMES_ROMAN: Font
    TIMES_BOLD: Font
    TIMES_ITALIC: Font
    TIMES_BOLD_ITALIC: Font
    COURIER: Font
    COURIER_BOLD: Font
    COURIER_OBLIQUE: Font
    COURIER_BOLD_OBLIQUE: Font
    SYMBOL: Font
    ZAPF_DINGBATS: Font

    def __repr__(self) -> str: ...

class EmbeddedFont:
    """A custom font embedded in a Document, with glyph-coverage diagnostics.

    Obtained from :meth:`Document.embedded_font`.
    """

    @property
    def name(self) -> str: ...
    def has_glyph(self, ch: str) -> bool: ...
    def missing_glyphs(self, text: str) -> list[str]: ...
    def __repr__(self) -> str: ...

# ── TextAlign ──────────────────────────────────────────────────────────────────

class TextAlign:
    """Text alignment options."""

    LEFT: TextAlign
    RIGHT: TextAlign
    CENTER: TextAlign
    JUSTIFIED: TextAlign

    def __repr__(self) -> str: ...

# ── Shadings (gradients, F65 / #297) ────────────────────────────────────────────
# Partial stubs: only enough to type :meth:`Page.add_shading`. The full
# construction surface (linear_gradient, radial_gradient, ShadingManager, …) is
# exposed at runtime but not yet modelled here.

class AxialShading: ...
class RadialShading: ...

# ── Page ───────────────────────────────────────────────────────────────────────

class Page:
    """A page in a PDF document for adding text and graphics content."""

    def __init__(self, width: float, height: float) -> None: ...

    @staticmethod
    def a4() -> Page: ...
    @staticmethod
    def a4_landscape() -> Page: ...
    @staticmethod
    def letter() -> Page: ...
    @staticmethod
    def letter_landscape() -> Page: ...
    @staticmethod
    def legal() -> Page: ...
    @staticmethod
    def legal_landscape() -> Page: ...

    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    @property
    def margins(self) -> Margins: ...

    def set_margins(self, margins: Margins) -> None: ...

    # Text operations
    def set_font(self, font: Font, size: float) -> None: ...
    def set_text_color(self, color: Color) -> None: ...
    def set_character_spacing(self, spacing: float) -> None: ...
    def set_word_spacing(self, spacing: float) -> None: ...
    def set_leading(self, leading: float) -> None: ...
    def text_at(self, x: float, y: float, text: str) -> None: ...

    # Graphics operations
    def set_fill_color(self, color: Color) -> None: ...
    def set_stroke_color(self, color: Color) -> None: ...
    def set_line_width(self, width: float) -> None: ...
    def set_fill_opacity(self, opacity: float) -> None: ...
    def set_stroke_opacity(self, opacity: float) -> None: ...
    def draw_rect(self, x: float, y: float, width: float, height: float) -> None: ...
    def draw_circle(self, cx: float, cy: float, radius: float) -> None: ...
    def move_to(self, x: float, y: float) -> None: ...
    def line_to(self, x: float, y: float) -> None: ...
    def curve_to(
        self, x1: float, y1: float, x2: float, y2: float, x3: float, y3: float
    ) -> None: ...
    def close_path(self) -> None: ...
    def fill(self) -> None: ...
    def stroke(self) -> None: ...
    def fill_and_stroke(self) -> None: ...

    # ── Gradient rendering (oxidize-pdf 2.14.0, #297) ────────────────────────
    def clip(self) -> None: ...
    def clip_even_odd(self) -> None: ...
    def end_path(self) -> None: ...
    def add_shading(
        self, name: str, shading: Union["AxialShading", "RadialShading"]
    ) -> None: ...
    def paint_shading(self, name: str) -> None: ...

    # Page-level colour-space resources (GFX-019, oxidize-pdf 2.11.0)
    def add_color_space(self, name: str, color_space: PageColorSpace) -> None: ...
    def set_fill_color_icc(self, name: str, components: list[float]) -> None: ...
    def set_stroke_color_icc(self, name: str, components: list[float]) -> None: ...
    def set_fill_color_calibrated_named(
        self, name: str, color: CalibratedColor
    ) -> None: ...
    def set_stroke_color_calibrated_named(
        self, name: str, color: CalibratedColor
    ) -> None: ...
    def set_fill_color_lab_named(self, name: str, color: LabColor) -> None: ...
    def set_stroke_color_lab_named(self, name: str, color: LabColor) -> None: ...

    def __repr__(self) -> str: ...

# ── Calibrated colour spaces (Feature 54) ───────────────────────────────────────

class CalGrayColorSpace:
    """CIE-based CalGray colour space (ISO 32000-1 §8.6.5.1)."""

    def __init__(self) -> None: ...
    @staticmethod
    def d50() -> CalGrayColorSpace: ...
    @staticmethod
    def d65() -> CalGrayColorSpace: ...
    def with_gamma(self, gamma: float) -> CalGrayColorSpace: ...
    def with_white_point(self, white_point: list[float]) -> CalGrayColorSpace: ...
    def with_black_point(self, black_point: list[float]) -> CalGrayColorSpace: ...
    @property
    def gamma(self) -> float: ...
    @property
    def white_point(self) -> tuple[float, float, float]: ...
    def __repr__(self) -> str: ...

class CalRgbColorSpace:
    """CIE-based CalRGB colour space (ISO 32000-1 §8.6.5.2)."""

    def __init__(self) -> None: ...
    @staticmethod
    def srgb() -> CalRgbColorSpace: ...
    @staticmethod
    def adobe_rgb() -> CalRgbColorSpace: ...
    @staticmethod
    def d65() -> CalRgbColorSpace: ...
    def with_gamma(self, gamma: list[float]) -> CalRgbColorSpace: ...
    def with_white_point(self, white_point: list[float]) -> CalRgbColorSpace: ...
    def with_matrix(self, matrix: list[float]) -> CalRgbColorSpace: ...
    @property
    def gamma(self) -> tuple[float, float, float]: ...
    def __repr__(self) -> str: ...

class LabColorSpace:
    """CIE Lab colour space (ISO 32000-1 §8.6.5.4)."""

    @staticmethod
    def d50() -> LabColorSpace: ...
    @staticmethod
    def d65() -> LabColorSpace: ...
    def __repr__(self) -> str: ...

class CalibratedColor:
    """A colour value in a calibrated (CalGray/CalRGB) colour space."""

    @staticmethod
    def cal_gray(value: float, cs: CalGrayColorSpace) -> CalibratedColor: ...
    @staticmethod
    def cal_rgb(rgb: list[float], cs: CalRgbColorSpace) -> CalibratedColor: ...
    def values(self) -> list[float]: ...
    def __repr__(self) -> str: ...

class LabColor:
    """A colour value in a Lab colour space."""

    def __init__(self, l: float, a: float, b: float, cs: LabColorSpace) -> None: ...
    @staticmethod
    def white() -> LabColor: ...
    @staticmethod
    def black() -> LabColor: ...
    @staticmethod
    def gray() -> LabColor: ...
    @property
    def l(self) -> float: ...
    @property
    def a(self) -> float: ...
    @property
    def b(self) -> float: ...
    def values(self) -> list[float]: ...
    def delta_e(self, other: LabColor) -> float: ...
    def __repr__(self) -> str: ...

# ── PageColorSpace (GFX-019) ────────────────────────────────────────────────────

class PageColorSpace:
    """A colour space registrable on a page via ``add_color_space`` and emitted
    at ``/Resources/ColorSpace/<name>`` (ISO 32000-1 §8.6)."""

    @staticmethod
    def device(name: str) -> PageColorSpace: ...
    @staticmethod
    def icc_based(n: int, alternate: str) -> PageColorSpace: ...
    @staticmethod
    def cal_gray(cs: CalGrayColorSpace) -> PageColorSpace: ...
    @staticmethod
    def cal_rgb(cs: CalRgbColorSpace) -> PageColorSpace: ...
    @staticmethod
    def lab(cs: LabColorSpace) -> PageColorSpace: ...
    @staticmethod
    def parameterised(family: str, params: dict[str, object]) -> PageColorSpace: ...
    def __repr__(self) -> str: ...

# ── Document ───────────────────────────────────────────────────────────────────

class Document:
    """A PDF document that can contain multiple pages and metadata."""

    def __init__(self) -> None: ...

    @property
    def page_count(self) -> int: ...
    @property
    def is_encrypted(self) -> bool: ...

    def set_title(self, title: str) -> None: ...
    def set_author(self, author: str) -> None: ...
    def set_subject(self, subject: str) -> None: ...
    def set_keywords(self, keywords: str) -> None: ...
    def set_creator(self, creator: str) -> None: ...
    def add_page(self, page: Page) -> None: ...
    def new_page_a4(self) -> Page: ...
    def new_page_letter(self) -> Page: ...
    def new_page(self, width: float, height: float) -> Page: ...
    def save(self, path: str) -> None: ...
    def save_to_bytes(self) -> bytes: ...
    def save_with_config(self, path: str, config: WriterConfig) -> None: ...
    def save_to_bytes_with_config(self, config: WriterConfig) -> bytes: ...
    def add_font(self, name: str, path: str) -> None: ...
    def add_font_from_bytes(self, name: str, data: bytes) -> None: ...
    def measure_text(self, text: str, font: Font, size: float) -> float: ...
    def measure_char(self, ch: str, font: Font, size: float) -> float: ...
    def embedded_font(self, name: str) -> Optional[EmbeddedFont]: ...
    def font_missing_glyphs(self, font_name: str, text: str) -> list[str]: ...
    def encrypt(
        self,
        user_password: str,
        owner_password: str,
        permissions: Optional[Permissions] = None,
    ) -> None: ...

    def __repr__(self) -> str: ...

# ── Form fields ───────────────────────────────────────────────────────────────

class TextField:
    """Single-line or multiline text input form field."""

    def __init__(self, name: str) -> None: ...

    def with_default_value(self, value: str) -> TextField: ...
    def with_value(self, value: str) -> TextField: ...
    def with_max_length(self, length: int) -> TextField: ...
    def multiline(self) -> TextField: ...
    def password(self) -> TextField: ...
    def with_default_appearance(
        self, font: Font, size: float, color: Color
    ) -> TextField: ...

    def __repr__(self) -> str: ...

class ComboBox:
    """Drop-down combo box form field, optionally editable."""

    def __init__(self, name: str) -> None: ...

    def add_option(self, export_value: str, display: str) -> ComboBox: ...
    def editable(self) -> ComboBox: ...
    def with_value(self, value: str) -> ComboBox: ...
    def with_default_appearance(
        self, font: Font, size: float, color: Color
    ) -> ComboBox: ...

    def __repr__(self) -> str: ...

# ── WriterConfig ───────────────────────────────────────────────────────────────

class WriterConfig:
    """Configuration for the PDF writer: compression, xref/object streams,
    target PDF version, and incremental-update mode."""

    def __init__(
        self,
        compress_streams: Optional[bool] = None,
        use_xref_streams: Optional[bool] = None,
        use_object_streams: Optional[bool] = None,
        pdf_version: Optional[str] = None,
        incremental_update: Optional[bool] = None,
    ) -> None: ...

    @staticmethod
    def modern() -> WriterConfig: ...
    @staticmethod
    def legacy() -> WriterConfig: ...
    @staticmethod
    def incremental() -> WriterConfig: ...

    @property
    def compress_streams(self) -> bool: ...
    @property
    def use_xref_streams(self) -> bool: ...
    @property
    def use_object_streams(self) -> bool: ...
    @property
    def pdf_version(self) -> str: ...
    @property
    def incremental_update(self) -> bool: ...

    def __repr__(self) -> str: ...

# ── ParseOptions ───────────────────────────────────────────────────────────────

class ParseOptions:
    """Configuration for the PDF parser (strictness, recovery, lenient modes)."""

    def __init__(
        self,
        strict_mode: bool = True,
        recover_from_stream_errors: bool = False,
        ignore_corrupt_streams: bool = False,
        partial_content_allowed: bool = False,
        lenient_streams: bool = False,
        lenient_encoding: bool = True,
        lenient_syntax: bool = False,
        max_recovery_attempts: int = 3,
        max_recovery_bytes: int = 1000,
        collect_warnings: bool = False,
    ) -> None: ...

    @staticmethod
    def strict() -> ParseOptions: ...
    @staticmethod
    def tolerant() -> ParseOptions: ...
    @staticmethod
    def lenient() -> ParseOptions: ...
    @staticmethod
    def skip_errors() -> ParseOptions: ...

    @property
    def strict_mode(self) -> bool: ...
    @property
    def recover_from_stream_errors(self) -> bool: ...
    @property
    def ignore_corrupt_streams(self) -> bool: ...
    @property
    def partial_content_allowed(self) -> bool: ...
    @property
    def lenient_streams(self) -> bool: ...
    @property
    def lenient_encoding(self) -> bool: ...
    @property
    def lenient_syntax(self) -> bool: ...
    @property
    def max_recovery_attempts(self) -> int: ...
    @property
    def max_recovery_bytes(self) -> int: ...
    @property
    def collect_warnings(self) -> bool: ...

    def __repr__(self) -> str: ...

# ── PdfReader ──────────────────────────────────────────────────────────────────

class PdfReader:
    """High-level PDF reader for parsing existing PDF files."""

    @staticmethod
    def open(path: str, options: Optional[ParseOptions] = ...) -> PdfReader: ...
    @staticmethod
    def from_bytes(data: bytes, options: Optional[ParseOptions] = ...) -> PdfReader: ...
    @staticmethod
    def from_stream(
        stream: BinaryIO, options: Optional[ParseOptions] = ...
    ) -> PdfReader: ...

    @property
    def is_encrypted(self) -> bool: ...
    @property
    def page_count(self) -> int: ...
    @property
    def version(self) -> str: ...

    def unlock(self, password: str) -> None: ...
    def get_page(self, index: int) -> ParsedPage: ...
    def get_page_resources(self, index: int) -> Optional[PageResources]: ...
    def get_page_content_streams(self, index: int) -> list[bytes]: ...
    def extract_text_from_page(self, index: int) -> str: ...
    def extract_text(self) -> list[str]: ...

    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

# ── ParsedPage ─────────────────────────────────────────────────────────────────

class ParsedPage:
    """A page obtained from parsing an existing PDF."""

    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    @property
    def rotation(self) -> int: ...

    def __repr__(self) -> str: ...

# ── Page resources ─────────────────────────────────────────────────────────────

class FontResource:
    """A font referenced by a page's ``/Resources /Font`` sub-dictionary."""

    @property
    def subtype(self) -> str: ...
    @property
    def base_font(self) -> str: ...
    @property
    def encoding(self) -> Optional[str]: ...
    @property
    def is_embedded(self) -> bool: ...
    @property
    def is_subset(self) -> bool: ...
    def __repr__(self) -> str: ...

class ImageResource:
    """An image (``/Subtype /Image`` XObject) referenced by a page's Resources."""

    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def bits_per_component(self) -> int: ...
    @property
    def filter(self) -> list[str]: ...
    @property
    def color_space(self) -> str: ...
    def __repr__(self) -> str: ...

class FormXObjectResource:
    """A Form XObject (``/Subtype /Form``) referenced by a page's Resources."""

    @property
    def bbox(self) -> Optional[tuple[float, float, float, float]]: ...
    def __repr__(self) -> str: ...

class PageResources:
    """Structured view of a page's ``/Resources`` dictionary."""

    @property
    def fonts(self) -> dict[str, FontResource]: ...
    @property
    def images(self) -> dict[str, ImageResource]: ...
    @property
    def forms(self) -> dict[str, FormXObjectResource]: ...
    @property
    def ext_g_states(self) -> dict[str, dict[str, object]]: ...
    @property
    def proc_sets(self) -> list[str]: ...
    @property
    def resource_keys(self) -> list[str]: ...
    def __repr__(self) -> str: ...

# ── Permissions ────────────────────────────────────────────────────────────────

class Permissions:
    """PDF document permissions for encrypted documents."""

    def __init__(
        self,
        print: bool = False,
        copy: bool = False,
        modify_contents: bool = False,
        modify_annotations: bool = False,
        fill_forms: bool = False,
        accessibility: bool = True,
        assemble: bool = False,
        print_high_quality: bool = False,
    ) -> None: ...

    @staticmethod
    def all() -> Permissions: ...
    @staticmethod
    def none() -> Permissions: ...

    @property
    def can_print(self) -> bool: ...
    @property
    def can_copy(self) -> bool: ...
    @property
    def can_modify_contents(self) -> bool: ...
    @property
    def can_modify_annotations(self) -> bool: ...
    @property
    def can_fill_forms(self) -> bool: ...
    @property
    def can_assemble(self) -> bool: ...
    @property
    def can_print_high_quality(self) -> bool: ...

    def __repr__(self) -> str: ...

# ── Operations ─────────────────────────────────────────────────────────────────

def split_pdf(input_path: str, output_dir: str) -> list[str]:
    """Split a PDF into individual single-page files.

    Args:
        input_path: Path to the input PDF file.
        output_dir: Directory where split pages will be written.

    Returns:
        A list of paths to the created files.

    Raises:
        PdfError: If the input file cannot be read or split.
        PdfIoError: If there is an I/O error.
    """
    ...

def merge_pdfs(input_paths: list[str], output_path: str) -> None:
    """Merge multiple PDF files into a single output file.

    Args:
        input_paths: List of paths to PDF files to merge (in order).
        output_path: Path where the merged PDF will be written.

    Raises:
        PdfError: If any input file cannot be read or the merge fails.
        PdfIoError: If there is an I/O error.
        ValueError: If the input list is empty.
    """
    ...

def rotate_pdf(input_path: str, output_path: str, degrees: int) -> None:
    """Rotate all pages of a PDF by the given angle.

    Args:
        input_path: Path to the input PDF file.
        output_path: Path where the rotated PDF will be written.
        degrees: Rotation angle in degrees. Must be 0, 90, 180, or 270.

    Raises:
        PdfError: If the rotation angle is invalid or the file cannot be processed.
        PdfIoError: If there is an I/O error.
    """
    ...

def extract_pages(input_path: str, output_path: str, page_indices: list[int]) -> None:
    """Extract specific pages from a PDF into a new file.

    Args:
        input_path: Path to the input PDF file.
        output_path: Path where the extracted pages will be written.
        page_indices: List of 0-based page indices to extract.

    Raises:
        PdfError: If a page index is out of bounds or the file cannot be processed.
        PdfIoError: If there is an I/O error.
        ValueError: If the page list is empty.
    """
    ...
